package com.gatech.services;

import com.gatech.services.parser.ImplementationGuide;
import com.gatech.services.parser.Synthea;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

import java.util.List;
import java.util.Map;

public class Helper {

    public void findMissingAttributeByProfile() {

        // Get all attribute from implementation
        ImplementationGuide implementationGuide = new ImplementationGuide();
        final JSONObject data = implementationGuide.readImplementationGuide("src/main/java/com/gatech/data/implementationGuide/us-core-patient.json");
        JSONObject snapshot = (JSONObject) data.get("snapshot");
        JSONArray element = (JSONArray) snapshot.get("element");
        final List<String> allAttributeOnImpGuide = implementationGuide.findAllElements(element);
        Object resource = implementationGuide.findResourceType(snapshot);

        // Get resource and it's json object from Synthea
        Synthea synthea = new Synthea();
        final Map<String, JSONObject> resourceAndJSON = synthea.findAttributeOnSynthea();
        //TODO: Now, we have the attribute from Implementation guide and profile generated by Synthea. Next step would be to fetch the differences.
    }

}
